name: auto-grading

on: [push]

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly

jobs:
  lab1-test:
    name: Lab1 Test
    runs-on: ubuntu-latest
    outputs:
      lab1_points: ${{ steps.lab1_points.outputs.lab1_points}}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: install dependencies
        run: |
          sudo apt-get update
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt-get install -y \
            wget \
            xxd \
            curl \
            gcc \
            g++ \
            make \
            libclang-dev \
            qemu-system-misc \
            bash \
            sudo \
            git \
            dosfstools \
            build-essential \
            pkg-config \
            libssl-dev \
            libz-dev \
            libclang-dev

      - uses: arceos-org/setup-musl@v1
        with:
          arch: riscv64

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2024-09-04
          components: rust-src, llvm-tools, clippy, rustfmt
          targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat, loongarch64-unknown-none

      - run: cargo install cargo-binutils

      - name: Run lab1
        id: lab1_points
        run: |
          qemu-system-riscv64 --version

          cd arceos || exit 1

          ./verify_lab1.sh | tee tmpa.txt

          lab1_score=$(grep -aoE 'Indicator: *[0-9]+' tmpa.txt | tail -n1 | grep -oE '[0-9]+') || true
          lab1_score=${lab1_score:-0}

          echo "lab1_points=$lab1_score" 
          echo "lab1_points=$lab1_score" >>"$GITHUB_OUTPUT"
          rm tmpa.txt -f

  deploy:
    name: Report Score to Server
    needs: lab1-test
    runs-on: ubuntu-latest

    steps:
      - name: Report Score
        env:
          lab1_score: ${{ needs.lab1-test.outputs.lab1_points }}
          total_score: 373
        run: |
          echo "Lab1: $lab1_score"

          score_json=$(jq -n \
            --arg channel "github" \
            --arg courseId "${{ secrets.ARCEOS_CHALLENGE_2025_AUTUMN_COURSE_ID }}" \
            --arg name "${{ github.actor }}" \
            --argjson score "$lab1_score" \
            --argjson totalScore "$total_score" \
            --arg ext "{}" \
            '{channel: $channel, courseId: $courseId, name: $name, score: $score, totalScore: $totalScore, ext: $ext}')

          response=$(curl -X POST "${{ secrets.COURSE_POST_API }}" \
            -H "accept: application/json;charset=utf-8" \
            -H "Content-Type: application/json" \
            -H "token: ${{ secrets.ARCEOS_CHALLENGE_2025_AUTUMN_TOKEN }}" \
            -d "$score_json" \
            -s)

          if echo "$response" | grep -q '"result":1'; then
            echo "成功：测试数据已发送"
          else
            echo "失败：接口返回异常"
            exit 1
          fi
